### ISSUE TITLE
Training scripts

### ISSUE THREAD

**Issue by xserban** [bhoov/flyvec#1]
Hi, do you plan to open source the scripts used to train flyvec?

**Comment by bhoov** [comment]
Thank you for your question! FlyVec was trained using code developed specifically for the PowerPC architecture that makes it hard to distribute (using similar training code to paper https://arxiv.org/abs/1908.08993). While I would like to re-implement this in PyTorch, I fear I will not have time in the upcoming weeks.

In the meantime, @DimaKrotov has created a demo notebook for example training in numpy that is available [here](https://github.com/DimaKrotov/Biological_Learning/blob/master/Unsupervised_learning_algorithm_MNIST.ipynb), and there is a new general-purpose Hebbian Learning wrapper around PyTorch Ignite available [here](https://github.com/Joxis/pytorch-hebbian) ([paper](https://arxiv.org/abs/2102.00428)).

**Comment by bhoov** [comment]
Past me underestimated the free time current me would have. I built a small wrapper around the training code for v0.3 (317bdac
), though you are on your own to build your own tokenizations. Please let me know if the instructions are unclear
