### ISSUE TITLE
Integrated DVC remote

### ISSUE THREAD

**Issue by deanp70** [bhoov/flyvec#3]
Hey @bhoov, I took a look at your project and it seems really cool. I remember reading about it when the paper came out. I'm working on a platform called [DAGsHub](https://DAGsHub.com) that combines Git, DVC, and MLflow and since your project uses DVC I thought I'd try my hand at migrating this project over, and you can see the migration here:
https://dagshub.com/Dean/flyvec

I pushed the data to DAGsHub storage which is a free integrated DVC remote so that you can view the content of your data folder from the UI. It can be connected to this GitHub in such a way that you push code here and data to DAGsHub.

Would love to hear your thoughts, and if you want me to transfer ownership to you on DAGsHub, I'd be happy to do that.

**Comment by bhoov** [comment]
Hi, this looks neat but I am not sure what motivation I would have to maintain another repository for the same code and data. Could you please expand on what benefits this system would offer me (as a dev) or other intended users?

**Comment by deanp70** [comment]
Thanks for the super quick response. It doesn't require you to maintain a separate repository. In this case, I disconnected the mirror (due to needing to change the dvc remote URL). Basically, you can connect your GitHub repository, so the code is automatically updated. Then you can push your DVC data to DAGsHub storage, or provide the S3 storage key.

The advantages would be that you can explore the data and download it directly from the UI.

As a side note, your project doesn't use experiment tracking and DVC pipelines (AFAICT) but if you did you could see it in the same UI.

Thanks again for your response, and would be happy to answer any other questions you might have.

**Comment by bhoov** [comment]
It sounds like a really neat tool, and I will definitely consider using it for a future project that would require tracking experiments. For now, though, I'd like to minimize additional technical overhead and keep things as they are for now. Thanks again for contacting me about this!
