### ISSUE TITLE
Context-dependent word embeddings

### ISSUE THREAD

**Issue by shermansiu** [bhoov/flyvec#5]
The Flyvec paper mentions that context-dependent word embeddings can be created, but it seems like the API only provides methods for context-independent embeddings. How can context-dependent word embeddings be created?

In particular, how can Figure 4 from the FlyVec paper be created?

It seems like the first half of Flyvec.synapses is the lookup table for the dense "context" word embeddings. Are these embeddings combined with the "target" word embedding to create the context-dependent word embedding? (e.g. by mean pooling, max pooling?)

**Comment by bhoov** [comment]
Please see [this readme](https://github.com/bhoov/flyvec/tree/master/flyvec#readme) for instructions on how to train with your own data.

The API that is published supports the interface at [flyvec.org](https://flyvec.org). It's purpose is to connect the tokenizer with the trained model and to analyze the learned associations.

**Comment by shermansiu** [comment]
I gave the paper a bit of a more thorough read and I still don't think training from scratch on my own data would help. Flyvec.synapses gives the **W** matrix as presented in the paper, which is all that is needed for both context and target block embeddings. The paper never really describes how the "context-dependent word embeddings" are created in-depth, which is what I was hoping the code would explain (perhaps the context and target embeddings are not pooled, just concatenated together?)

If the published API supports the interface at flyvec.org, how is the phrase embedding created? Is the hash code embedding simply created by summing/averaging the dense embeddings of each word in the phrase and then taking the top k activations, or what?

**Comment by shermansiu** [comment]
In the paper, it says, "In the static case, the input **v_A** has all zeros in the context block and a one-hot encoded word
in the target block." Okay, so as the code suggests, we just take the embedding from the target block and use that as the static word embedding.

"In the context-dependent case, both blocks have binary encoded input words.
Importantly, both context-dependent and static embeddings are mapped into the same space of sparse
binary hash codes (a vector of K elements, with k ones in it)," but how are they aggregated to form the embedding? The paper seems to suggest that all embeddings are of the form **Wv_A**, but it never specifically says that the embeddings are created that way. In fact, it only explains how the context-dependent embeddings are created by defining what **v_A** is in the context-independent and context-dependent cases.

The above suggests that the embeddings are added together, but it would be nice to get official confirmation. (Also, summing and mean pooling would give the same hash code embedding if only the top k activations are set to 1 during sparsification).

**Comment by shermansiu** [comment]
Summing the dense embeddings (and excluding the embeddings of stop words), and then sparsifying works quite well.

The context embeddings are quite similar to the target embeddings, so I just use target embeddings to allow for token sizes of arbitrary length (and not just odd-length ones).

**Comment by bhoov** [comment]
Context dependent word embeddings and target word embeddings are very related and require two things:

- the **W** synapse matrix of shape `(H, 2*V)` where `H` is the embedding dimension and `V` is the vocabulary size. The second dimension accounts for each token appearing as the target word embedding or a token appearing in the context of another target embedding.
- the **q** query vector of shape `(2*V,)`. In a context independent case, this will be a one hot vector where the token is a `1` in the target compartment and zeros everywhere else. If you are seeking a context dependent word embedding, this vector will be `1` in the context compartment for every token that appears in the bag of words (there is no position encoded in these embeddings). Optionally, one of the tokens in the bag of words can be considered a target word.

As the operation to extract the word embedding is a dot product, this is equivalent to saying "sum the embeddings" above. However, the dot product also allows you to adjust the query, say if multiple of the same token appear in the context, or if you want the target token in a query to have greater weight than the context.

I apologize for any confusion, I hope this clears it up

**Comment by shermansiu** [comment]
No worries!

Yeah, I've been using  **Wq** embeddings this whole time.

Good point, we aren't constrained to having odd-length windows as described in the paper and the target word doesn't have to be in the middle of the window, as it's just a bag of words anyway. I suppose including the counts of each word in each component of the **q** vector instead of using each component as an indicator variable effectively makes us take the weighted average/sum (which are equivalent anyways after sparsification as we only care about what the top k values are).

On a side note, the original vocabulary is a lot smaller than I originally anticipated. For example, not even "flute" is part of the vocabulary. I guess I might need to look into retraining a model anyways...
